##注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
##网关名称
spring:
  application:
    name: springcloud-zuul
##配置网关反向代理
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-api-a
    api-b:
      path: /api-b/**
      serviceId: springcloud-api-b
